server:
  port: 8901
  
mybatis: 
  type-aliases-package: com.example.model
 
spring: 
  datasource:
    url: jdbc:mysql:///base_sql?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123